theme: jekyll-theme-minimal
title: Pílulas do Gee
description: Dados, informações e códigos para te auxiliar no aprendizado do uso de linguagens de programação e ferramentas para sensoriamento remoto e sistemas de informação geográfica.